const fs = require('fs');
function helpMessage() {
    let hasil = "*Help Utilitas* :\n\n";
    hasil += "~> *!list surah* :\n";
    hasil += "daftar nomor surah Al-Quran\n\n";
    hasil += "~> *!list surah 2* :\n";
    hasil += "daftar nomor surah Al-Quran page 2\n\n";
    hasil += "~> *!help admin* :\n";
    hasil += "daftar fasilitas Admin BOT\n\n";
    hasil += "~> *!help public* :\n";
    hasil += "daftar fasilitas non-Admin\n\n";
    hasil += "~> *!bug report [laporan]* :\n";
    hasil += "laporan bug ke Owner BOT\n";
    hasil += "_contoh_ : *!bug report !gtts bermasalah*\n\n";
    hasil += "~> *!media* :\n";
    hasil += "daftar fasilitas Media BOT\n\n\n";
    hasil += "creator : *@itzngga*";
    return hasil;
}
exports.helpMessage = helpMessage();
function helpAdmin1() {
    let hasil = "*Help Admin Page 1* :\n\n";
    hasil += "~> *!everyone* :\n";
    hasil += "mention semua anggota group\n\n";
    hasil += "~> *!arsip* :\n";
    hasil += "arsipkan chat agar privasi tetap terjaga\n\n";
    hasil += "~> *!desc [teks]* :\n";
    hasil += "mengganti deskripsi group\n\n";
    hasil += "~> *!subject* :\n";
    hasil += "mengganti nama group\n\n";
    hasil += "~> *!delete* :\n";
    hasil += "menghapus chat bot dengan reply\n\n";
    hasil += "~> *!resend* :\n";
    hasil += "mengirim foto/video dengan reply\n\n";
    hasil += "~> *!quoteinfo* :\n";
    hasil += "mengirim info chat dengan reply\n\n";
    hasil += "~> *!mediainfo* :\n";
    hasil += "mengirim info media dengan reply\n\n";
    hasil += "~> *!join [link group] :*\n";
    hasil += "bergabung ke group melalui link\n\n";
    hasil += "~> *!help admin 2* :\n";
    hasil += "utilitas admin page ke-2\n\n\n";
    hasil += "creator : *@itzngga*";
    return hasil;
}
exports.helpAdmin1 = helpAdmin1();
function helpPublic() {
    let hasil = "*Public Help* :\n\n";
    hasil += "~> *!mute* :\n";
    hasil += "mute bot jika dirasa spam\n\n";
    hasil += "~> *!unmute* :\n";
    hasil += "unmute bot jika anda butuh\n\n";
    hasil += "~> *!arsip* :\n";
    hasil += "arsipkan chat agar privasi terjaga\n\n";
    hasil += "~> *!kick [tag]* :\n";
    hasil += "kick member dalam group, syarat :\n";
    hasil += "1.BOT harus admin group\n";
    hasil += "2.Pengirim harus admin group\n";
    hasil += "_contoh_ : *!kick @Bambang*\n\n";
    hasil += "~> *!me* :\n";
    hasil += "bot menyapa anda\n\n";
    hasil += "~> *!location* :\n";
    hasil += "lokasi google\n\n";
    hasil += "~> *!info* :\n";
    hasil += "informasi detail bot\n\n";
    hasil += "~> *!groupinfo* :\n";
    hasil += "informasi detail group\n\n";
    hasil += "~> *@bot* :\n";
    hasil += "untuk tes keaktifan bot\n\n";
    hasil += "~> *@p* :\n";
    hasil += "untuk tes keaktifan bot\n\n";
    hasil += "~> *!media* :\n";
    hasil += "daftar utilitas media bot\n\n\n";
    hasil += "creator : *@itzngga*";
    return hasil;
}
exports.helpPublic = helpPublic();
function helpAdmin2() {
    let hasil = "*Admin Help 2* :\n\n";
    hasil += "~> *!mute* :\n";
    hasil += "mute bot jika dirasa spam\n\n";
    hasil += "~> *!unmute* :\n";
    hasil += "unmute bot jika anda butuh\n\n";
    hasil += "~> *!typing* :\n";
    hasil += "bot mensimulasikan Mengetik..\n\n";
    hasil += "~> *!recording* :\n";
    hasil += "bot mensimulasikan Merekam..\n\n";
    hasil += "~> *!clear* :\n";
    hasil += "bot tidak mensimulasikan apa2\n\n";
    hasil += "~> *!arsip* :\n";
    hasil += "arsipkan chat agar privasi terjaga\n\n";
    hasil += "~> *!me* :\n";
    hasil += "bot menyapa anda\n\n";
    hasil += "~> *!location* :\n";
    hasil += "lokasi google\n\n";
    hasil += "~> *!info* :\n";
    hasil += "informasi detail bot\n\n";
    hasil += "~> *!groupinfo* :\n";
    hasil += "informasi detail group\n\n";
    hasil += "~> *@bot* :\n";
    hasil += "untuk tes keaktifan bot\n\n";
    hasil += "~> *@p* :\n";
    hasil += "untuk tes keaktifan bot\n\n";
    hasil += "~> *!media* :\n";
    hasil += "daftar utilitas media bot\n\n\n";
    hasil += "creator : *@itzngga*";
    return hasil;
}
exports.helpAdmin2 = helpAdmin2();
function helpMedia() {
    let hasil = "*Media Help* :\n\n";
    hasil += "~> *!google [pencarian]* :\n";
    hasil += "mencari ke google\n";
    hasil += "_contoh_ : *!google berapa umur bumi*\n\n";
    hasil += "~> *?simsimi* :\n";
    hasil += "panduan cara menggunakan simsimi\n\n";
    hasil += "~> *!cekresi [nomor resi] [kurir]* :\n";
    hasil += "cek resi paket\n";
    hasil += "_contoh_ : *!cekresi 0123456789012 jnt*\n\n";
    hasil += "~> *!corona* :\n";
    hasil += "informasi covid19 dunia & indonesia\n\n";
    hasil += "~> *!ipcheck [ip]* :\n";
    hasil += "cek ip target (mungkin tidak akurat)\n";
    hasil += "_contoh_ : *!ipcheck 192.168.0.1*\n\n";
    hasil += "~> *!ceknama [nama]* :\n";
    hasil += "arti nama (hiburan)\n";
    hasil += "_contoh_ : *!ceknama bambang*\n\n";
    hasil += "~> *!igstalk [username]* :\n";
    hasil += "stalk instagram doi\n";
    hasil += "_contoh_ : *!igstalk @itzngga* atau\n";
    hasil += "_contoh_ : *!igstalk itzngga*\n\n";
    hasil += "~> *!bmkg* :\n";
    hasil += "informasi gempa > 5.1 SR terbaru\n\n";
    hasil += "~> *!quran* :\n";
    hasil += "ayat acak dari Al-Quran\n\n";
    hasil += "~> *!lang [bahasa] [teks]* :\n";
    hasil += "Google Text To Speech dengan bahasa spesifik\n";
    hasil += "_contoh_ : *lang en hello*\n\n";
    hasil += "~> *!gtts [kata]* :\n";
    hasil += "Google Text To Speech dengan bahasa Indonesia\n";
    hasil += "_contoh_ : *!gtts halo guys*\n\n";
    hasil += "~> *!kbbi [kata]* :\n";
    hasil += "mencari arti kata menurut KBBI\n";
    hasil += "_contoh_ : *!kbbi kamu*\n\n";
    hasil += "~> *!surah [nomor surah]* :\n";
    hasil += "informasi surah dalam Al-Quran\n";
    hasil += "_contoh_ : *!surah 1*\n\n";
    hasil += "~> *!surah [no surah] ayat [parameter]* :\n";
    hasil += "menampilkan ayat Al-Quran menurut nomor surah\n";
    hasil += "*Parameter* :\n";
    hasil += "*1*. 1 (ayat single)\n";
    hasil += "*2*. 1,3,6 (ayat pilihan)\n";
    hasil += "*3*. 1-10 (ayat urutan)\n";
    hasil += "_contoh_ : *!surah 1 ayat 1-7*\n\n";
    hasil += "~> *!1cak* :\n";
    hasil += "gambar meme random dari 1cak\n\n";
    hasil += "~> *?apakah [pertanyaan]* :\n";
    hasil += "kerang ajaib, hasil : Iya,Tidak, Mungkin\n";
    hasil += "_contoh_ : *?apakah aku ganteng?*\n\n";
    hasil += "~> *?kapan [pertanyaan]* :\n";
    hasil += "kerang ajaib, hasil : Kata Verba umum\n\n";
    hasil += "_contoh_ : *?kapan nikah?*\n\n";
    hasil += "~> *!nuked* :\n";
    hasil += "kode nuklir 6 digit random\n\n\n";
    hasil += "creator : *@itzngga*";
    return hasil;
}
exports.helpMedia = helpMedia();
function helpSimSimi() {
    let hasil = "*Apa Itu SimSimi?* :\n\n";
    hasil += "Simsimi adalah chatbot yang membalas seperti layaknya manusia biasa dengan kecerdasan buatan, simsimi dirancang untuk menjadi bot yang tidak mengikuti topik dan kadang juga tidak jelas\n\n";
    hasil += "*Panduan Pengunaan SimSimi* :\n\n";
    hasil += "~> *!simsimi* :\n";
    hasil += "Memulai chat simsimi di manapun anda berada\n\n";
    hasil += "~> *!simsimi stop* :\n";
    hasil += "Menghentikan chat simsimi\n\n\n";
    hasil += "creator : *itzngga*";
    return hasil;
}
exports.helpSimSimi = helpSimSimi();
function listSurah() {
    let hasil = fs.readFileSync('surah1.txt', {encoding: 'utf-8'});
    return hasil;
}
exports.listSurah = listSurah();
function listSurah2() {
    let hasil = fs.readFileSync('surah2.txt', {encoding: 'utf-8'});
    return hasil;
}
exports.listSurah2 = listSurah2();